# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import carla_pb2 as carla__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in carla_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CarlaSimStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/carla_api.CarlaSim/Ping',
                request_serializer=carla__pb2.Empty.SerializeToString,
                response_deserializer=carla__pb2.Pong.FromString,
                _registered_method=True)
        self.Init = channel.unary_unary(
                '/carla_api.CarlaSim/Init',
                request_serializer=carla__pb2.InitRequest.SerializeToString,
                response_deserializer=carla__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/carla_api.CarlaSim/Reset',
                request_serializer=carla__pb2.ResetRequest.SerializeToString,
                response_deserializer=carla__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/carla_api.CarlaSim/Step',
                request_serializer=carla__pb2.StepRequest.SerializeToString,
                response_deserializer=carla__pb2.StepResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/carla_api.CarlaSim/Stop',
                request_serializer=carla__pb2.Empty.SerializeToString,
                response_deserializer=carla__pb2.Empty.FromString,
                _registered_method=True)
        self.ShouldQuit = channel.unary_unary(
                '/carla_api.CarlaSim/ShouldQuit',
                request_serializer=carla__pb2.Empty.SerializeToString,
                response_deserializer=carla__pb2.ShouldQuitResponse.FromString,
                _registered_method=True)


class CarlaSimServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Check if the server is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Initialize the simulation (e.g., load maps, set weather)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset the simulation with a new scenario
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Advance the simulation by one step with the provided control command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop the simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShouldQuit(self, request, context):
        """Check if the simulation should quit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarlaSimServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=carla__pb2.Empty.FromString,
                    response_serializer=carla__pb2.Pong.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=carla__pb2.InitRequest.FromString,
                    response_serializer=carla__pb2.InitResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=carla__pb2.ResetRequest.FromString,
                    response_serializer=carla__pb2.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=carla__pb2.StepRequest.FromString,
                    response_serializer=carla__pb2.StepResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=carla__pb2.Empty.FromString,
                    response_serializer=carla__pb2.Empty.SerializeToString,
            ),
            'ShouldQuit': grpc.unary_unary_rpc_method_handler(
                    servicer.ShouldQuit,
                    request_deserializer=carla__pb2.Empty.FromString,
                    response_serializer=carla__pb2.ShouldQuitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'carla_api.CarlaSim', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('carla_api.CarlaSim', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarlaSim(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla_api.CarlaSim/Ping',
            carla__pb2.Empty.SerializeToString,
            carla__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla_api.CarlaSim/Init',
            carla__pb2.InitRequest.SerializeToString,
            carla__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla_api.CarlaSim/Reset',
            carla__pb2.ResetRequest.SerializeToString,
            carla__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla_api.CarlaSim/Step',
            carla__pb2.StepRequest.SerializeToString,
            carla__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla_api.CarlaSim/Stop',
            carla__pb2.Empty.SerializeToString,
            carla__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShouldQuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carla_api.CarlaSim/ShouldQuit',
            carla__pb2.Empty.SerializeToString,
            carla__pb2.ShouldQuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
