# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: position.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'position.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eposition.proto\x12\tcarla_api\"Z\n\x08Position\x12%\n\x04lane\x18\x01 \x01(\x0b\x32\x17.carla_api.LanePosition\x12\'\n\x05world\x18\x02 \x01(\x0b\x32\x18.carla_api.WorldPosition\"e\n\rWorldPosition\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01h\x18\x04 \x01(\x01\x12\t\n\x01p\x18\x05 \x01(\x01\x12\t\n\x01r\x18\x06 \x01(\x01\x12\x12\n\nh_relative\x18\x07 \x01(\x01\"u\n\x0cLanePosition\x12\x0f\n\x07road_id\x18\x01 \x01(\x05\x12\x0f\n\x07lane_id\x18\x02 \x01(\x05\x12\t\n\x01s\x18\x03 \x01(\x01\x12\x0e\n\x06offset\x18\x04 \x01(\x01\x12\x18\n\x0bjunction_id\x18\x05 \x01(\x05H\x00\x88\x01\x01\x42\x0e\n\x0c_junction_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'position_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSITION']._serialized_start=29
  _globals['_POSITION']._serialized_end=119
  _globals['_WORLDPOSITION']._serialized_start=121
  _globals['_WORLDPOSITION']._serialized_end=222
  _globals['_LANEPOSITION']._serialized_start=224
  _globals['_LANEPOSITION']._serialized_end=341
# @@protoc_insertion_point(module_scope)
