# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: av_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'av_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import config_pb2 as config__pb2
from . import control_pb2 as control__pb2
from . import empty_pb2 as empty__pb2
from . import object_pb2 as object__pb2
from . import pong_pb2 as pong__pb2
from . import scenario_pb2 as scenario__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61v_server.proto\x12\tsbsvf_api\x1a\x0c\x63onfig.proto\x1a\rcontrol.proto\x1a\x0b\x65mpty.proto\x1a\x0cobject.proto\x1a\npong.proto\x1a\x0escenario.proto\"\xe6\x03\n\x10\x41vServerMessages\x1a\x30\n\x0bInitRequest\x12!\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x11.sbsvf_api.Config\x1a,\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\x1a\x87\x01\n\x0cResetRequest\x12\x12\n\noutput_dir\x18\x01 \x01(\t\x12.\n\rscenario_pack\x18\x02 \x01(\x0b\x32\x17.sbsvf_api.ScenarioPack\x12\x33\n\x13initial_observation\x18\x03 \x03(\x0b\x32\x16.sbsvf_api.ObjectState\x1a\x35\n\rResetResponse\x12$\n\x08\x63trl_cmd\x18\x01 \x01(\x0b\x32\x12.sbsvf_api.CtrlCmd\x1aP\n\x0bStepRequest\x12+\n\x0bobservation\x18\x01 \x03(\x0b\x32\x16.sbsvf_api.ObjectState\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x03\x1a\x34\n\x0cStepResponse\x12$\n\x08\x63trl_cmd\x18\x01 \x01(\x0b\x32\x12.sbsvf_api.CtrlCmd\x1a)\n\x12ShouldQuitResponse\x12\x13\n\x0bshould_quit\x18\x01 \x01(\x08\x32\xc5\x03\n\x08\x41vServer\x12)\n\x04Ping\x12\x10.sbsvf_api.Empty\x1a\x0f.sbsvf_api.Pong\x12Y\n\x04Init\x12\'.sbsvf_api.AvServerMessages.InitRequest\x1a(.sbsvf_api.AvServerMessages.InitResponse\x12\\\n\x05Reset\x12(.sbsvf_api.AvServerMessages.ResetRequest\x1a).sbsvf_api.AvServerMessages.ResetResponse\x12Y\n\x04Step\x12\'.sbsvf_api.AvServerMessages.StepRequest\x1a(.sbsvf_api.AvServerMessages.StepResponse\x12*\n\x04Stop\x12\x10.sbsvf_api.Empty\x1a\x10.sbsvf_api.Empty\x12N\n\nShouldQuit\x12\x10.sbsvf_api.Empty\x1a..sbsvf_api.AvServerMessages.ShouldQuitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'av_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVSERVERMESSAGES']._serialized_start=115
  _globals['_AVSERVERMESSAGES']._serialized_end=601
  _globals['_AVSERVERMESSAGES_INITREQUEST']._serialized_start=135
  _globals['_AVSERVERMESSAGES_INITREQUEST']._serialized_end=183
  _globals['_AVSERVERMESSAGES_INITRESPONSE']._serialized_start=185
  _globals['_AVSERVERMESSAGES_INITRESPONSE']._serialized_end=229
  _globals['_AVSERVERMESSAGES_RESETREQUEST']._serialized_start=232
  _globals['_AVSERVERMESSAGES_RESETREQUEST']._serialized_end=367
  _globals['_AVSERVERMESSAGES_RESETRESPONSE']._serialized_start=369
  _globals['_AVSERVERMESSAGES_RESETRESPONSE']._serialized_end=422
  _globals['_AVSERVERMESSAGES_STEPREQUEST']._serialized_start=424
  _globals['_AVSERVERMESSAGES_STEPREQUEST']._serialized_end=504
  _globals['_AVSERVERMESSAGES_STEPRESPONSE']._serialized_start=506
  _globals['_AVSERVERMESSAGES_STEPRESPONSE']._serialized_end=558
  _globals['_AVSERVERMESSAGES_SHOULDQUITRESPONSE']._serialized_start=560
  _globals['_AVSERVERMESSAGES_SHOULDQUITRESPONSE']._serialized_end=601
  _globals['_AVSERVER']._serialized_start=604
  _globals['_AVSERVER']._serialized_end=1057
# @@protoc_insertion_point(module_scope)
