# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sim_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sim_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import config_pb2 as config__pb2
from . import control_pb2 as control__pb2
from . import empty_pb2 as empty__pb2
from . import object_pb2 as object__pb2
from . import path_pb2 as path__pb2
from . import pong_pb2 as pong__pb2
from . import scenario_pb2 as scenario__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sim_server.proto\x12\tsbsvf_api\x1a\x0c\x63onfig.proto\x1a\rcontrol.proto\x1a\x0b\x65mpty.proto\x1a\x0cobject.proto\x1a\npath.proto\x1a\npong.proto\x1a\x0escenario.proto\"\xb3\x04\n\x11SimServerMessages\x1a<\n\x0bInitRequest\x12!\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x11.sbsvf_api.Config\x12\n\n\x02\x64t\x18\x02 \x01(\x01\x1a,\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\x1a\xc8\x01\n\x0cResetRequest\x12\x12\n\noutput_dir\x18\x01 \x01(\t\x12.\n\rscenario_pack\x18\x02 \x01(\x0b\x32\x17.sbsvf_api.ScenarioPack\x12\x45\n\x06params\x18\x03 \x03(\x0b\x32\x35.sbsvf_api.SimServerMessages.ResetRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x38\n\rResetResponse\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\x16.sbsvf_api.ObjectState\x1aI\n\x0bStepRequest\x12$\n\x08\x63trl_cmd\x18\x01 \x01(\x0b\x32\x12.sbsvf_api.CtrlCmd\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x03\x1a\x37\n\x0cStepResponse\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\x16.sbsvf_api.ObjectState\x1a)\n\x12ShouldQuitResponse\x12\x13\n\x0bshould_quit\x18\x01 \x01(\x08\x32\xcd\x03\n\tSimServer\x12)\n\x04Ping\x12\x10.sbsvf_api.Empty\x1a\x0f.sbsvf_api.Pong\x12[\n\x04Init\x12(.sbsvf_api.SimServerMessages.InitRequest\x1a).sbsvf_api.SimServerMessages.InitResponse\x12^\n\x05Reset\x12).sbsvf_api.SimServerMessages.ResetRequest\x1a*.sbsvf_api.SimServerMessages.ResetResponse\x12[\n\x04Step\x12(.sbsvf_api.SimServerMessages.StepRequest\x1a).sbsvf_api.SimServerMessages.StepResponse\x12*\n\x04Stop\x12\x10.sbsvf_api.Empty\x1a\x10.sbsvf_api.Empty\x12O\n\nShouldQuit\x12\x10.sbsvf_api.Empty\x1a/.sbsvf_api.SimServerMessages.ShouldQuitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sim_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMSERVERMESSAGES_RESETREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_SIMSERVERMESSAGES_RESETREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_SIMSERVERMESSAGES']._serialized_start=128
  _globals['_SIMSERVERMESSAGES']._serialized_end=691
  _globals['_SIMSERVERMESSAGES_INITREQUEST']._serialized_start=149
  _globals['_SIMSERVERMESSAGES_INITREQUEST']._serialized_end=209
  _globals['_SIMSERVERMESSAGES_INITRESPONSE']._serialized_start=211
  _globals['_SIMSERVERMESSAGES_INITRESPONSE']._serialized_end=255
  _globals['_SIMSERVERMESSAGES_RESETREQUEST']._serialized_start=258
  _globals['_SIMSERVERMESSAGES_RESETREQUEST']._serialized_end=458
  _globals['_SIMSERVERMESSAGES_RESETREQUEST_PARAMSENTRY']._serialized_start=413
  _globals['_SIMSERVERMESSAGES_RESETREQUEST_PARAMSENTRY']._serialized_end=458
  _globals['_SIMSERVERMESSAGES_RESETRESPONSE']._serialized_start=460
  _globals['_SIMSERVERMESSAGES_RESETRESPONSE']._serialized_end=516
  _globals['_SIMSERVERMESSAGES_STEPREQUEST']._serialized_start=518
  _globals['_SIMSERVERMESSAGES_STEPREQUEST']._serialized_end=591
  _globals['_SIMSERVERMESSAGES_STEPRESPONSE']._serialized_start=593
  _globals['_SIMSERVERMESSAGES_STEPRESPONSE']._serialized_end=648
  _globals['_SIMSERVERMESSAGES_SHOULDQUITRESPONSE']._serialized_start=650
  _globals['_SIMSERVERMESSAGES_SHOULDQUITRESPONSE']._serialized_end=691
  _globals['_SIMSERVER']._serialized_start=694
  _globals['_SIMSERVER']._serialized_end=1155
# @@protoc_insertion_point(module_scope)
