# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sim_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sim_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import control_pb2 as control__pb2
from . import object_pb2 as object__pb2
from . import scenario_pb2 as scenario__pb2
from . import path_pb2 as path__pb2
from . import config_pb2 as config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sim_server.proto\x12\tsbsvf_api\x1a\rcontrol.proto\x1a\x0cobject.proto\x1a\x0escenario.proto\x1a\npath.proto\x1a\x0c\x63onfig.proto\"\x07\n\x05\x45mpty\"\x13\n\x04Pong\x12\x0b\n\x03msg\x18\x01 \x01(\t\"<\n\x0bInitRequest\x12!\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x11.sbsvf_api.Config\x12\n\n\x02\x64t\x18\x02 \x01(\x01\",\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"I\n\x0bStepRequest\x12$\n\x08\x63trl_cmd\x18\x01 \x01(\x0b\x32\x12.sbsvf_api.CtrlCmd\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x03\"7\n\x0cStepResponse\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\x16.sbsvf_api.ObjectState\"\xb6\x01\n\x0cResetRequest\x12\x12\n\noutput_dir\x18\x01 \x01(\t\x12.\n\rscenario_pack\x18\x02 \x01(\x0b\x32\x17.sbsvf_api.ScenarioPack\x12\x33\n\x06params\x18\x03 \x03(\x0b\x32#.sbsvf_api.ResetRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"8\n\rResetResponse\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\x16.sbsvf_api.ObjectState\")\n\x12ShouldQuitResponse\x12\x13\n\x0bshould_quit\x18\x01 \x01(\x08\x32\xcf\x02\n\tSimServer\x12)\n\x04Ping\x12\x10.sbsvf_api.Empty\x1a\x0f.sbsvf_api.Pong\x12\x37\n\x04Init\x12\x16.sbsvf_api.InitRequest\x1a\x17.sbsvf_api.InitResponse\x12:\n\x05Reset\x12\x17.sbsvf_api.ResetRequest\x1a\x18.sbsvf_api.ResetResponse\x12\x37\n\x04Step\x12\x16.sbsvf_api.StepRequest\x1a\x17.sbsvf_api.StepResponse\x12*\n\x04Stop\x12\x10.sbsvf_api.Empty\x1a\x10.sbsvf_api.Empty\x12=\n\nShouldQuit\x12\x10.sbsvf_api.Empty\x1a\x1d.sbsvf_api.ShouldQuitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sim_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESETREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_RESETREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=102
  _globals['_EMPTY']._serialized_end=109
  _globals['_PONG']._serialized_start=111
  _globals['_PONG']._serialized_end=130
  _globals['_INITREQUEST']._serialized_start=132
  _globals['_INITREQUEST']._serialized_end=192
  _globals['_INITRESPONSE']._serialized_start=194
  _globals['_INITRESPONSE']._serialized_end=238
  _globals['_STEPREQUEST']._serialized_start=240
  _globals['_STEPREQUEST']._serialized_end=313
  _globals['_STEPRESPONSE']._serialized_start=315
  _globals['_STEPRESPONSE']._serialized_end=370
  _globals['_RESETREQUEST']._serialized_start=373
  _globals['_RESETREQUEST']._serialized_end=555
  _globals['_RESETREQUEST_PARAMSENTRY']._serialized_start=510
  _globals['_RESETREQUEST_PARAMSENTRY']._serialized_end=555
  _globals['_RESETRESPONSE']._serialized_start=557
  _globals['_RESETRESPONSE']._serialized_end=613
  _globals['_SHOULDQUITRESPONSE']._serialized_start=615
  _globals['_SHOULDQUITRESPONSE']._serialized_end=656
  _globals['_SIMSERVER']._serialized_start=659
  _globals['_SIMSERVER']._serialized_end=994
# @@protoc_insertion_point(module_scope)
